version: '2'

services:
    db:
        container_name: sf_pgsql
        image: postgres:9
        volumes:
            - "./data/db:/var/lib/postgresql"
        environment:
            POSTGRES_DB: ${DB}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
    redis:
        container_name: sf_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4
    php:
        container_name: sf_phpfpm
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - "80:8000"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - redis
            - db
            - centrifugo
    nodejs:
        container_name: sf_nodejs
        image: node:alpine
        user: "node"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        working_dir: /var/www/symfony
    centrifugo:
        container_name: sf_centrifugo
        image: centrifugo/centrifugo
        command: centrifugo -c config.yml -w --port=8000  --log_level=debug --debug --insecure --address=0.0.0.0
        ports:
            - "8000:8000"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5
        volumes:
            - ./centrifugo/config.yml:/centrifugo/config.yml   # centrifugo -c config.json -w /opt/centrifugo/web
    rabbit:
        container_name: sf_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6
networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
